# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main


pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  lean: true

- script
   git remote add gitlab https://gitlab.com/leonardo247Project/rn_azure_test.git

    git fetch --no-tags --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/gitlab/*

    git checkout -b import-gitlab

    git commit --allow-empty -m "Add empty commit"

    git merge --no-edit --allow-unrelated-histories --strategy-option=theirs remotes/gitlab/master

    git push origin import-gitlab:master

  env:

    GIT_ASKPASS: /usr/bin/true

    GIT_HTTP_USERNAME: $(GITLAB_TOKEN)

    GIT_HTTP_PASSWORD: x-oauth-basic

  displayName: 'Import GitLab repository'