# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script:  git clone --mirror $(https://github.com/ResmiADevi/AWS-PROJECT.git) temp-repo
    cd temp-repo
    git remote add azure $(https://dev.azure.com/financial-application/fmt-web/_git/myrepository)
    git push --mirror azure
  displayName: 'Migrate repository to Azure Repos'

- script: 
   rm -rf temp-repo  
  displayName: "cleanup"